# Generated by Django 4.1.7 on 2023-04-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zaunita', '0003_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
